version: '2.1'
services:
  postgres:
    container_name: postgres-exceptionmanager-it
    image: postgres:13
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq-exceptionmanager-it
    image: rabbitmq:3.8-management
    ports:
      - "34369:4369"
      - "55672:25672"
      - "35671:5671"
      - "35672:5672"
      - "46671:15671"
      - "46672:15672"
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/opt/definitions.json
